development:
  adapter: mysql2
  database: db/aqualuks-development
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: db/aqualuks-test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: db/aqualuks-production
  pool: 5
  timeout: 5000
